# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "de2a92a9507209a8b9dd3a24bd215d44"
name = "studyperks-app"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customers,read_discounts,read_products,read_themes,write_checkouts,write_customers,write_discounts,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
