# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "54edb70aa006e3a59b83fc154b832133"
name = "StudyPerks"
application_url = "https://app.studyperks.me"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"


[access_scopes]
scopes = "read_discounts,write_discounts,read_orders,read_products"

[auth]
redirect_urls = [
  "https://app.studyperks.me/auth/callback",
  "https://studyperks-shopify-app-production.up.railway.app/auth/callback"
]
